apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      # volumeMounts:
      #   - mountPath: "/usr/share/nginx/html"
      #     name: my-pvc
      # - name: php
      #   image: own-image-with-php-backend:v1.0
      #   command: ["/usr/local/sbin/php-fpm","-F"]
      #   workingDir: /var/www
      #   resources:
      #     requests:
      #       cpu: "100m"        
      #       memory: "100Mi"   
      #     limits:
      #       cpu: "100m"        
      #       memory: 100Mi"  
      # docker run --name nginx_myproject -p 8080:80 -v /home/webuser/myproject/www:/usr/share/nginx/html -v /home/webuser/myproject/nginx_logs:/var/log/nginx -d nginx